<?php
return [
    'ua-od' => 'Odessa',
    'ua-ks' => 'Kherson',
    'ua-kc' => 'Kiev City',
    'ua-zt' => 'Zhytomyr',
    'ua-sm' => 'Sumy',
    'ua-dt' => 'Donets\'k',
    'ua-dp' => 'Dnipropetrovs\'k',
    'ua-kk' => 'Kharkiv',
    'ua-lh' => 'Luhans\'k',
    'ua-pl' => 'Poltava',
    'ua-zp' => 'Zaporizhzhya',
    'ua-sc' => 'Sevastopol',
    'ua-kr' => 'Crimea',
    'ua-ch' => 'Chernihiv',
    'ua-rv' => 'Rivne',
    'ua-cv' => 'Chernivtsi',
    'ua-if' => 'Ivano-Frankivs\'k',
    'ua-km' => 'Khmel\'nyts\'kyy',
    'ua-lv' => 'L\'viv',
    'ua-tp' => 'Ternopil',
    'ua-zk' => 'Transcarpathia',
    'ua-vo' => 'Volyn',
    'ua-ck' => 'Cherkasy',
    'ua-kh' => 'Kirovohrad',
    'ua-kv' => 'Kiev',
    'ua-mk' => 'Mykolayiv',
    'ua-vi' => 'Vinnytsya',
];
